# Generated by Django 5.2.3 on 2025-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(max_length=1000),
        ),
    ]
